# Generated by Django 4.2.7 on 2023-12-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contact',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('none', 'none')], default='none', max_length=10, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.IntegerField(blank=True, max_length=12, null=True, verbose_name='phone'),
        ),
    ]
