# Generated by Django 4.2.7 on 2023-12-29 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productions', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=255, verbose_name='customer name')),
                ('so_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='Online Sale NO:')),
                ('purchased_date', models.DateTimeField()),
                ('purchased_shop', models.CharField(max_length=100, verbose_name='shop')),
                ('qty', models.SmallIntegerField(verbose_name='qty')),
                ('accessories', models.CharField(max_length=200)),
                ('user_dmg', models.CharField(max_length=255, verbose_name='physical damage')),
                ('reason', models.TextField()),
                ('how', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(max_length=30, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productions.product')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Servicing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding', models.TextField()),
                ('checked', models.BooleanField(default=False)),
                ('fnl_decision', models.CharField(max_length=250)),
                ('fees', models.IntegerField(default=0)),
                ('fees_by', models.CharField(choices=[('comp', 'company'), ('cust', 'customer')], default='comp', max_length=40, verbose_name='fees_by')),
                ('approved', models.BooleanField(blank=True, default=False, verbose_name='approved')),
                ('done', models.BooleanField(blank=True, default=False, verbose_name='approved')),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.errorreturn')),
                ('technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.technician')),
            ],
        ),
    ]
