# Generated by Django 4.2.7 on 2023-12-29 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('publisher', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='product name')),
                ('price', models.IntegerField(verbose_name='price')),
                ('warranty', models.IntegerField(choices=[(3, '3months'), (6, '6months'), (9, '9months'), (12, '12months'), (15, '15months'), (18, '18months'), (21, '21months')], verbose_name='warranty')),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40, verbose_name='Feature:')),
                ('value', models.CharField(max_length=100, verbose_name='value')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec', to='productions.product')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='promotion event')),
                ('started_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('dis_percent', models.FloatField()),
                ('discount', models.FloatField(default=0.0)),
                ('items', models.ManyToManyField(to='productions.product')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('catalog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog', to='productions.catalog')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='productions.catalogcategory')),
            ],
        ),
    ]
